# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://bawaggroup-app-prod.crm4.dynamics.com/'
        user-name: 'tarik.dedic@bawagpsk.com'
        password-secret: ${{ secrets.BAWAGPASSWORD }}
        solution-name: PIPVotingtool
        solution-output-file: 'PIPVotingtool.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: 'out/PIPVotingtool.zip'
        solution-folder: 'out/solutions/PIP Voting tool'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v0
      with:
        environment-url: 'https://org12a5ebf5.crm4.dynamics.com/'
        user-name: 'tarik.dedic@inzpire.ba'
        password-secret: ${{ secrets.PASSWORD }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: 'out/solutions/PIP Voting tool'
        solution-target-folder: 'src/solutions/PIPVotingtool'
        token: ${{ secrets.TOKEN }}
